apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jax-inventory-data-pvc
  labels:
    app: jax-inventory
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: fast-ssd

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jax-inventory-results-pvc
  labels:
    app: jax-inventory
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Gi
  storageClassName: fast-ssd
