# Inventory Problem Configuration
inventory:
  # Problem parameters
  problem:
    lead_time: 7  # days
    service_level: 0.95
    max_inventory: 1000
    max_order: 500

  # Cost parameters
  costs:
    holding_cost: 1.0      # cost per unit per period
    stockout_penalty: 10.0  # penalty cost per unit short
    fixed_order_cost: 50.0  # fixed cost per order
    variable_cost: 2.0      # cost per unit ordered

  # Demand parameters
  demand:
    base_demand: 50.0
    demand_std: 15.0
    seasonality_amplitude: 0.3
    trend_rate: 0.01
    promotion_probability: 0.05
    promotion_multiplier: 2.0

  # Simulation parameters
  simulation:
    horizon: 365  # days
    warmup_period: 30
    num_episodes: 100
    random_seed: 42